import { cityNames } from "./neighborhoods";
import generatedCities from "../data/us-cities.generated.json";

// Cities we currently have real neighborhood data for (the "● live" ones).
export const LIVE_CITIES = new Set(cityNames);

export function hasLiveData(city: string): boolean {
  return LIVE_CITIES.has(city);
}

/**
 * The full type-ahead list: every ingested live city plus the complete US
 * Census "Places" gazetteer (~32k "City, ST" strings) generated by
 * scripts/build-us-cities.mjs via the ingestion GitHub Action. No hand-written
 * entries — all API data.
 */
export const usCities: string[] = Array.from(
  new Set([...cityNames, ...(generatedCities as string[])])
).sort((a, b) => a.localeCompare(b));
